# Generated by Django 5.0.6 on 2024-06-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('spz', models.CharField(max_length=10, unique=True)),
                ('znacka', models.CharField(max_length=50)),
                ('typ', models.CharField(max_length=50)),
                ('generace', models.CharField(max_length=20)),
                ('rok_vydani', models.IntegerField()),
                ('vykon', models.IntegerField(help_text='Výkon v kW')),
                ('barva', models.CharField(max_length=30)),
                ('pohon', models.CharField(max_length=30)),
                ('najeto_km', models.IntegerField()),
                ('hodnota_auta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fotka', models.ImageField(blank=True, null=True, upload_to='fotky_aut')),
            ],
        ),
    ]
