# Generated by Django 5.0.6 on 2024-06-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Majitel',
            fields=[
                ('id_majitel', models.AutoField(primary_key=True, serialize=False)),
                ('rodne_cislo', models.CharField(max_length=10, unique=True)),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('pohlavi', models.CharField(choices=[('M', 'Muž'), ('Z', 'Žena')], max_length=1)),
                ('mesto', models.CharField(max_length=100)),
                ('ulice', models.CharField(max_length=100)),
                ('cislo_popisne', models.CharField(max_length=10)),
                ('fotka', models.ImageField(blank=True, null=True, upload_to='majitele/')),
            ],
        ),
    ]
