# Generated by Django 5.0.6 on 2024-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_majitel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vyrobce',
            fields=[
                ('id_vyrobce', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100)),
                ('mesto', models.CharField(max_length=100)),
                ('ulice', models.CharField(max_length=100)),
                ('cislo_popisne', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vyrobci/')),
            ],
        ),
    ]
