# Generated by Django 5.0.6 on 2024-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vyrobce'),
    ]

    operations = [
        migrations.AddField(
            model_name='vyrobce',
            name='zeme',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
