# Generated by Django 5.0.6 on 2024-06-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vyrobce_zeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='majitel_auta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.majitel'),
        ),
        migrations.AddField(
            model_name='auto',
            name='vyrobce_auta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vyrobce'),
        ),
    ]
